# Generated by Django 4.1.4 on 2022-12-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tabla_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
